"""Append manually-authored HMDA question cards into the live `cards` table.

This is the DuckDB equivalent of Step 4 in NEW_DATASET_RUNBOOK.md ("Append into
the live cards table") / Section 4 Step D in DATASET_INTEGRATION.md
("swap_cards"), adapted for a source where the positive/negative questions
were written by hand instead of generated by the LLM regenerators +
validate_questions.

What it does, per the runbook's contract:
  - reads your two question CSVs (table-level, variable-level)
  - joins each row to `tables` / `variables` to pull measure_type / subject_area /
    l1_domains / depth / is_total (denormalized onto the card, same as Census)
  - joins to `coverage` (filtered to status='success') to collapse the years and
    geo_levels a card applies to into the years_available / geo_levels_available
    JSON arrays, at (table_id, dataset) granularity
  - inserts one card row per (table_id, dataset, variable_id, text), with
    target_year = NULL and embedded_at = NULL (so build_embedding_index picks it
    up next)
  - is idempotent: reruns anti-join against existing (target_table_id,
    target_dataset, target_variable_id, text) so you can re-run after fixing a
    CSV without creating duplicate cards

Card types / weights follow the same vocabulary already used by Census cards
(see build_cards.py / DATASET_INTEGRATION.md Section 3 weight table), so
nothing downstream (router, card-type filters, analysis notebooks) needs to
change:

    table_question_canonical   weight=1.5   positive
    table_question_negative    weight=1.0   negative
    var_question               weight=2.0   positive
    var_question_negative      weight=1.0   negative

Expected CSV columns:
    table_questions.csv    -> table_id, dataset, polarity, text
    variable_questions.csv -> table_id, dataset, variable_id, polarity, text

Usage:
    python -m tools.append_hmda_cards --dry-run \
        --dataset gcs/hmda_v1 \
        --table-csv data/staging/hmda_table_questions.csv \
        --variable-csv data/staging/hmda_variable_questions.csv

    python -m tools.append_hmda_cards \
        --metadata-db data/metadata/search_index.duckdb \
        --dataset gcs/hmda_v1 \
        --table-csv data/staging/hmda_table_questions.csv \
        --variable-csv data/staging/hmda_variable_questions.csv \
        -v
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import duckdb

logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_METADATA_DB = REPO_ROOT / "data" / "metadata" / "search_index.duckdb"


def _csv_view_sql(view_name: str, csv_path: Path) -> str:
    """DuckDB can't bind a prepared-statement parameter inside CREATE VIEW,
    so the path is inlined (escaped) rather than passed positionally."""
    escaped = str(csv_path).replace("'", "''")
    return (
        f"CREATE OR REPLACE TEMP VIEW {view_name} AS "
        f"SELECT * FROM read_csv_auto('{escaped}', header=true)"
    )


# ---------------------------------------------------------------------------
# Schema (mirrors the SQLite `cards` table in build_cards.py / DATASET_INTEGRATION.md,
# translated to DuckDB DDL — same columns, same semantics)
# ---------------------------------------------------------------------------

_CARDS_DDL = """
CREATE SEQUENCE IF NOT EXISTS cards_rowid_seq START 1;

CREATE TABLE IF NOT EXISTS cards (
    rowid                 BIGINT PRIMARY KEY DEFAULT nextval('cards_rowid_seq'),
    card_type             VARCHAR NOT NULL,
    text                  VARCHAR NOT NULL,

    target_table_id       VARCHAR NOT NULL,
    target_dataset        VARCHAR NOT NULL,
    target_year           INTEGER,                 -- always NULL; years live in years_available
    target_variable_id    VARCHAR,                 -- NULL for table cards

    weight                DOUBLE NOT NULL DEFAULT 1.0,
    polarity              VARCHAR NOT NULL DEFAULT 'positive',

    years_available       VARCHAR NOT NULL DEFAULT '[]',      -- JSON array
    geo_levels_available  VARCHAR NOT NULL DEFAULT '[]',      -- JSON array

    measure_type          VARCHAR,
    subject_area          VARCHAR,
    l1_domains            VARCHAR,
    depth                 INTEGER,
    is_total              INTEGER,
    is_commonly_queried   INTEGER,
    kind                  VARCHAR,

    embedded_at           DOUBLE,
    embedding_version     VARCHAR
);

CREATE INDEX IF NOT EXISTS idx_cards_target
    ON cards(target_table_id, target_dataset, target_variable_id);
CREATE INDEX IF NOT EXISTS idx_cards_type
    ON cards(card_type);
CREATE INDEX IF NOT EXISTS idx_cards_unembedded
    ON cards(embedded_at);
"""


def ensure_schema(con: duckdb.DuckDBPyConnection) -> None:
    con.execute(_CARDS_DDL)


# ---------------------------------------------------------------------------
# Coverage collapse: (table_id, dataset) -> years_available / geo_levels_available
# ---------------------------------------------------------------------------

def _register_coverage_view(con: duckdb.DuckDBPyConnection) -> None:
    """One row per (table_id, dataset) with sorted-JSON years/geo_levels,
    computed only from coverage rows with status='success' — exactly the
    _load_coverage_maps / _json_years_for logic swap_cards.py uses for Census."""
    con.execute("""
        CREATE OR REPLACE TEMP VIEW coverage_agg AS
        SELECT
            table_id,
            dataset,
            to_json(list_sort(list(DISTINCT year)))      AS years_available,
            to_json(list_sort(list(DISTINCT geo_level)))  AS geo_levels_available
        FROM coverage
        WHERE status = 'success'
        GROUP BY table_id, dataset
    """)


# ---------------------------------------------------------------------------
# Table-level cards
# ---------------------------------------------------------------------------

def append_table_question_cards(
    con: duckdb.DuckDBPyConnection,
    csv_path: Path,
    *, dataset: str,
    weight_positive: float = 1.5,
    weight_negative: float = 1.0,
) -> int:
    con.execute(_csv_view_sql("_staged_table", csv_path))

    before = con.execute("SELECT COUNT(*) FROM cards").fetchone()[0]

    sql = """
    INSERT INTO cards
      (card_type, text, target_table_id, target_dataset, target_variable_id,
       weight, polarity, years_available, geo_levels_available,
       measure_type, subject_area, l1_domains, depth, is_total)
    SELECT
      CASE WHEN LOWER(s.polarity) = 'negative'
           THEN 'table_question_negative' ELSE 'table_question_canonical' END,
      s.text,
      s.table_id, s.dataset, NULL,
      CASE WHEN LOWER(s.polarity) = 'negative'
           THEN ? ELSE ? END,
      LOWER(s.polarity),
      COALESCE(cov.years_available, '[]'),
      COALESCE(cov.geo_levels_available, '[]'),
      t.measure_type, t.subject_area, t.l1_domains_json,
      NULL, NULL
    FROM _staged_table s
    JOIN tables t
      ON t.table_id = s.table_id AND t.dataset = s.dataset
    LEFT JOIN coverage_agg cov
      ON cov.table_id = s.table_id AND cov.dataset = s.dataset
    WHERE s.dataset = ?
      -- idempotent: skip rows already carded
      AND NOT EXISTS (
        SELECT 1 FROM cards c
        WHERE c.target_table_id = s.table_id
          AND c.target_dataset = s.dataset
          AND c.target_variable_id IS NULL
          AND c.text = s.text
      )
    """
    con.execute(sql, [weight_negative, weight_positive, dataset])
    after = con.execute("SELECT COUNT(*) FROM cards").fetchone()[0]
    return after - before


# ---------------------------------------------------------------------------
# Variable-level cards
# ---------------------------------------------------------------------------

def append_variable_question_cards(
    con: duckdb.DuckDBPyConnection,
    csv_path: Path,
    *, dataset: str,
    weight_positive: float = 2.0,
    weight_negative: float = 1.0,
) -> int:
    con.execute(_csv_view_sql("_staged_var", csv_path))

    before = con.execute("SELECT COUNT(*) FROM cards").fetchone()[0]

    sql = """
    INSERT INTO cards
      (card_type, text, target_table_id, target_dataset, target_variable_id,
       weight, polarity, years_available, geo_levels_available,
       measure_type, subject_area, l1_domains, depth, is_total,
       is_commonly_queried, kind)
    SELECT
      CASE WHEN LOWER(s.polarity) = 'negative'
           THEN 'var_question_negative' ELSE 'var_question' END,
      s.text,
      s.table_id, s.dataset, s.variable_id,
      CASE WHEN LOWER(s.polarity) = 'negative'
           THEN ? ELSE ? END,
      LOWER(s.polarity),
      COALESCE(cov.years_available, '[]'),
      COALESCE(cov.geo_levels_available, '[]'),
      t.measure_type, t.subject_area, t.l1_domains_json,
      v.depth, v.is_total, v.is_commonly_queried, v.kind
    FROM _staged_var s
    JOIN variables v
      ON v.table_id = s.table_id AND v.dataset = s.dataset
     AND v.variable_id = s.variable_id
    JOIN tables t
      ON t.table_id = s.table_id AND t.dataset = s.dataset
    LEFT JOIN coverage_agg cov
      ON cov.table_id = s.table_id AND cov.dataset = s.dataset
    WHERE s.dataset = ?
      AND v.is_commonly_queried = 1
      -- idempotent: skip rows already carded
      AND NOT EXISTS (
        SELECT 1 FROM cards c
        WHERE c.target_table_id = s.table_id
          AND c.target_dataset = s.dataset
          AND c.target_variable_id = s.variable_id
          AND c.text = s.text
      )
    """
    con.execute(sql, [weight_negative, weight_positive, dataset])
    after = con.execute("SELECT COUNT(*) FROM cards").fetchone()[0]
    return after - before


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def run(
    metadata_db: Path,
    dataset: str,
    table_csv: Path | None = None,
    variable_csv: Path | None = None,
    dry_run: bool = False,
) -> dict:
    metadata_db.parent.mkdir(parents=True, exist_ok=True)
    con = duckdb.connect(str(metadata_db))
    try:
        ensure_schema(con)
        _register_coverage_view(con)

        if dry_run:
            stats = {}
            if table_csv:
                con.execute(_csv_view_sql("_preview_t", table_csv))
                stats["table_questions_in_csv"] = con.execute(
                    "SELECT COUNT(*) FROM _preview_t WHERE dataset = ?", [dataset]
                ).fetchone()[0]
            if variable_csv:
                con.execute(_csv_view_sql("_preview_v", variable_csv))
                stats["variable_questions_in_csv"] = con.execute(
                    "SELECT COUNT(*) FROM _preview_v WHERE dataset = ?", [dataset]
                ).fetchone()[0]
            logger.info("[dry-run] no rows inserted")
            return stats

        stats: dict = {}
        if table_csv:
            n = append_table_question_cards(con, table_csv, dataset=dataset)
            stats["table_question_cards_inserted"] = n
            logger.info("table question cards inserted: %d", n)

        if variable_csv:
            n = append_variable_question_cards(con, variable_csv, dataset=dataset)
            stats["variable_question_cards_inserted"] = n
            logger.info("variable question cards inserted: %d", n)

        stats["total_cards_for_dataset"] = con.execute(
            "SELECT COUNT(*) FROM cards WHERE target_dataset = ?", [dataset]
        ).fetchone()[0]
        stats["pending_embedding"] = con.execute(
            "SELECT COUNT(*) FROM cards WHERE target_dataset = ? "
            "AND embedded_at IS NULL",
            [dataset],
        ).fetchone()[0]
        return stats
    finally:
        con.close()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("--metadata-db", default=str(DEFAULT_METADATA_DB))
    ap.add_argument(
        "--dataset", required=True,
        help="Namespace for the HMDA data, e.g. 'gcs/hmda_v1' — must match the "
             "dataset column already populated in tables/variables/coverage.",
    )
    ap.add_argument("--table-csv", type=Path, default=None,
                     help="CSV of table-level positive/negative questions.")
    ap.add_argument("--variable-csv", type=Path, default=None,
                     help="CSV of variable-level positive/negative questions.")
    ap.add_argument("--dry-run", action="store_true",
                     help="Show row counts only, insert nothing.")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )

    if not args.table_csv and not args.variable_csv:
        logger.error("Provide at least one of --table-csv / --variable-csv.")
        return 1

    stats = run(
        metadata_db=Path(args.metadata_db),
        dataset=args.dataset,
        table_csv=args.table_csv,
        variable_csv=args.variable_csv,
        dry_run=args.dry_run,
    )
    for k, v in stats.items():
        print(f"{k}: {v}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
